name: Monitoramento Oficial CEFET
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions: # Dá permissão para o robô salvar arquivos no seu GitHub
      contents: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar script
        run: npx tsx index.ts
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

      - name: Salvar progresso
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -f last_content.txt  # O '-f' força a inclusão mesmo estando no .gitignore
          git commit -m "Bot: Atualizando último conteúdo verificado" || echo "Sem alterações para salvar"
          git push
